app1/urls.py
from django.conf.urls import url

from . import views

app_name = "app1"
urlpatterns = [
    #url(r'^contact/$', views.contact_view, name="contact_view"),
    #url(r'^appinfo/$', views.appinfo_view, name="appinfo_view"),

    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),

]

powtorka1/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^app1/', include('app1.urls')),
    url(r'^app1/contact/', include('app1.urls')),
    url(r'^app1/appinfo/', include('app1.urls')),
    url(r'^admin/', admin.site.urls),

]

questionnaire/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.main_view, name="main_view"),
    url(r'^contact/$', views.contact_view, name="contact_view"),
    url(r'^appinfo/$', views.appinfo_view, name="appinfo_view"),

    url(r'^(?P<question_id>[0-9]+)/$', views.detail_view, name="detail_view"),
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results_view, name="results_view"),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote_view, name="vote_view"),


]

app1/models.py
from django.db import models
import datetime # for was_published_recently
from django.utils import timezone # for was_published_recently

# Create your models here.

class MyQuestion(models.Model):
    question_text = models.CharField(max_length = 200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now-datetime.timedelta(days=1) <=self.pub_date <= now
        #return self.pub_date>= timezone.now()-datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.shord_description = 'Published recently?'

class MyChoice(models.Model):
    question = models.ForeignKey(MyQuestion, on_delete = models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

app1/views.py
from django.http import HttpResponseRedirect, HttpResponse
from .models import MyQuestion, MyChoice
# from django.shortcuts import render # it is common idiom to load a template
from django.template import loader
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone


class IndexView(generic.ListView):
    template_name = 'app1/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return MyQuestion.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]
        #return MyQuestion.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = MyQuestion
    template_name = 'app1/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return MyQuestion.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = MyQuestion
    template_name = 'app1/results.html'

def vote(request, question_id):
    question = get_object_or_404(MyQuestion, pk=question_id)
    try:
        selected_choice = question.mychoice_set.get(pk=request.POST['choice'])
    except (KeyError, MyChoice.DoesNotExist):
        return render(request, 'app1/detail.html', {
        'question':question,
        'error_message': "You didn't select choice.",
        })
    else:
        selected_choice.votes +=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('app1:results', args=(question.id,)))
    #return HttpResponse("You are at the vote_view and You are looking at question %s" % question_id)

app1/templates/app1/detail.html
<h1>{{ myquestion.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'app1:vote' myquestion.id %}" method="post">
{% csrf_token %}
{% for choice in myquestion.mychoice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

app1/templates/app1/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'app1/style.css' %}" />


{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'app1:detail' question.id %}">{{question.question_text }} </a>   <br>(published: {{ question.pub_date }})</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No app1 are available.</p>
{% endif %}

app1/templates/app1/results.html
<h1>{{ myquestion.question_text }}</h1>

<ul>
{% for choice in myquestion.mychoice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'app1:detail' myquestion.id %}">Vote again?</a>